Log:
  dir: "log/"
  link_name: "latest_log.log"
  level: "info"
  report_caller: false
  format: "2006-01-02 15:04:05.000000"
  writer:
    - name: "Info"
      path: "%Y%m%d_%H%M.log"
      max_age: 480
      rotation_time: 2
    - name: "Warn"
      path: "warn/%Y%m%d_%H%M.log"
      max_age: 480
      rotation_time: 2
  write_map:
    panic: "Warn"
    fatal: "Warn"
    error: "Warn"
    warn: "Warn"
    info: "Info"
    debug: "Info"
Data:
  save: true
  dir: "data/"
  max_age: 480
  rotation_time: 2
GRPCServer:
  port: "1687"
  host: "localhost"
Websocket:
  - exchange: "binance"
    url: "wss://stream.bybit.com/v5/public/spot"
    host_type: "spot"
    ws_pool_size: 1
    subscribe: 
    reconn_time: -1
    cmd:
      - method: "depth"
        params:
          symbol: "BTCUSDT"
          limit: 5
    publisher:
      - topic: "orderbook"
        skey: 158
        size: 1073741 #1GB
        store: true
      - topic: "Trade"
        skey: 258
        size: 1073741 #1GB
        store: true
      - topic: "ticker"
        skey: 358
        size: 1073741 #1GB
        store: true
